name: check-reservations

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4,14 * * *' # Runs at 04:00 UTC (00:00 EST) and 14:00 UTC (10:00 EST) every day

jobs:
  scheduled:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
    - name: check out this repo
      uses: actions/checkout@v3
    - name: setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: install python packages
      run: |-
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: execute script
      env: 
        RESY_API_KEY: ${{ secrets.RESY_API_KEY }}
      run: python reservations.py
    - name: send email
      env: 
        FROM_ADDRESS: ${{ secrets.FROM_ADDRESS }}
        FROM_ADDRESS_PASSWORD: ${{ secrets.FROM_ADDRESS_PASSWORD }}
      run: python send_email.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "github-actions"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data retrieved at: ${timestamp}" || exit 0
        git push
